name: Laravel CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Получение кода
        uses: actions/checkout@v3

      - name: Установка PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, bcmath, pdo, sqlite, dom

      - name: Установка зависимостей Composer
        run: composer install --no-progress --prefer-dist --optimize-autoloader

      - name: Подготовка базы данных SQLite
        run: |
          mkdir -p database
          touch database/database.sqlite
        shell: bash

      - name: Копирование .env
        run: cp .env.example .env

      - name: Генерация ключа приложения
        run: php artisan key:generate

      - name: Запуск миграций
        run: php artisan migrate --force

      - name: Запуск тестов
        run: php artisan test

